// ---------------------------------------------------------------------------
// `peaks memory reindex` — full rebuild of `.peaks/memory/index.json` from
// the markdown files on disk, plus regeneration of the human/LLM-facing
// `MEMORY.md` index and a drift report.
//
// Why this exists (slice 2026-09-09-memory-system-overhaul, B):
//   - `peaks memory extract` only ever wrote memories FROM artifacts; it
//     never re-scanned files already on disk, and there was no rebuild
//     command. 78 top-level files were absent from index.json.
//   - The index's `kind` came only from the nested `metadata.type` field;
//     files using a top-level `kind:` were silently dropped.
//   - `index.json` (machine) and `MEMORY.md` (human/LLM) were two
//     unsynchronised indexes with nothing keeping them in sync.
//
// Contract:
//   - read-only on the memory markdown files (never rewrites a memory body)
//   - deterministic ordering: kinds in `KIND_ORDER`, entries by name
//   - nothing is silently dropped: every file that could not be classified
//     is reported with its path + raw value
//   - `MEMORY.md` is regenerated with a "do not edit" banner (the previous
//     hand-maintained index had drifted to 116 lines against 231 index
//     entries; a derived view is the only way to keep them in sync)
// ---------------------------------------------------------------------------

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';

import type { MemoryIndex, MemoryIndexEntry, ProjectMemoryKind } from '../types.js';
import { MEMORY_KIND_TIER } from '../types.js';
import { parseMemoryFrontmatter, parseStoredMemoryFile } from '../parsers/frontmatter.js';
import { summarizeMemoryBody } from '../parsers/markdown-pure.js';
import { assertSafeProjectMemoryDir, normalizeRoot } from '../store/paths.js';
import { buildMemoryIndex, generateMemoryIndexFile, readExistingIndex } from './ranking.js';
import { listMarkdownFiles, readProjectMemories } from './search.js';

/** Marker line that owns `MEMORY.md`. Anything above it is machine output. */
export const MEMORY_MD_BANNER = '<!-- generated by `peaks memory reindex` — do not edit -->';

/** `MEMORY.md` is the generated index itself — never a memory source. */
export const MEMORY_MD_FILENAME = 'MEMORY.md';

/**
 * Deterministic section order for the generated `MEMORY.md`: hot kinds
 * first (mirrors `HOT_KINDS` in `ranking.ts`), warm kinds last. Derived
 * from the insertion order of `MEMORY_KIND_TIER` so the vocabulary has
 * exactly one definition.
 */
export const KIND_ORDER: readonly ProjectMemoryKind[] =
  Object.keys(MEMORY_KIND_TIER) as ProjectMemoryKind[];

export interface ReindexUnclassified {
  name: string;
  filePath: string;
  /** The first raw type/kind value found in the frontmatter (null when absent). */
  rawKind: string | null;
  reason: string;
}

export interface ReindexOrphanEntry {
  name: string;
  kind: string;
  /** The `sourcePath` recorded in the previous index that no longer exists on disk. */
  sourcePath: string;
}

/**
 * Two or more different files resolve to the same memory name (after the
 * `name:` → `title:` → filename-stem fallback chain). Reported, never
 * resolved by overwriting: both files keep their own index entry, and the
 * collision is surfaced so a human/LLM can rename one of them.
 */
export interface ReindexNameConflict {
  name: string;
  /** Every file that resolves to this name, sorted. Always length >= 2. */
  filePaths: string[];
}

export interface MemoryReindexReport {
  apply: boolean;
  projectRoot: string;
  memoryDir: string;
  indexPath: string;
  memoryMdPath: string;
  /** Markdown files scanned (excludes the generated `MEMORY.md`). */
  scannedFiles: number;
  /** Files represented in the rebuilt index. */
  indexed: number;
  indexedByKind: Record<string, number>;
  /** Files on disk with no resolvable kind — reported, never invented. */
  unclassified: ReindexUnclassified[];
  /** Distinct files that resolve to the same index name — reported, never overwritten. */
  nameConflicts: ReindexNameConflict[];
  /** Previous index entries whose `sourcePath` no longer exists (error-class drift). */
  orphanIndex: ReindexOrphanEntry[];
  /** Files on disk that the rebuilt index does not contain (warn-class drift). */
  orphanDisk: string[];
  memoryMd: { path: string; regenerated: boolean };
  writtenFiles: string[];
}

export interface MemoryReindexOptions {
  projectRoot: string;
  apply?: boolean;
}

function emptyKindCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const kind of KIND_ORDER) counts[kind] = 0;
  return counts;
}

function readPreviousIndexEntries(indexPath: string): MemoryIndexEntry[] {
  // `readExistingIndex` is fail-soft (null on missing / unparsable / wrong
  // version), which is exactly what a drift report wants: a corrupt index
  // simply yields no orphan-index findings instead of throwing.
  const previous = readExistingIndex(indexPath) as (MemoryIndex & { cold?: MemoryIndexEntry[] }) | null;
  if (previous === null) return [];
  return [
    ...Object.values(previous.hot ?? {}).flat(),
    ...Object.values(previous.warm ?? {}).flat(),
    ...(previous.cold ?? [])
  ];
}

function collectUnclassified(diskFiles: readonly string[]): ReindexUnclassified[] {
  const unclassified: ReindexUnclassified[] = [];
  for (const filePath of diskFiles) {
    let parsed;
    try {
      parsed = parseMemoryFrontmatter(readFileSync(filePath, 'utf8'));
    } catch {
      // Unreadable file: still report it rather than dropping it silently.
      unclassified.push({ name: basename(filePath, '.md'), filePath, rawKind: null, reason: 'file could not be read' });
      continue;
    }
    if (parsed.kind.kind !== null) continue;
    const rawKind = parsed.kind.rawKind;
    unclassified.push({
      name: parsed.name ?? basename(filePath, '.md'),
      filePath,
      rawKind,
      reason: rawKind === null
        ? 'no metadata.type / kind / type field in frontmatter'
        : `unrecognized kind value: ${rawKind}`
    });
  }
  return unclassified.sort((left, right) => left.filePath.localeCompare(right.filePath));
}

/**
 * Detect files that resolve to the same memory name. Only files the read
 * path actually indexes participate (a file rejected for a missing kind is
 * not an index entry and cannot collide with one).
 *
 * Deterministic: names sorted, each `filePaths` sorted. Never resolves the
 * collision itself — the caller reports it; both files keep their entries.
 */
function collectNameConflicts(diskFiles: readonly string[]): ReindexNameConflict[] {
  const byName = new Map<string, string[]>();
  for (const filePath of diskFiles) {
    let parsed;
    try {
      parsed = parseStoredMemoryFile(readFileSync(filePath, 'utf8'), filePath);
    } catch {
      continue; // unreadable files are reported by collectUnclassified
    }
    if (parsed === null) continue;
    const bucket = byName.get(parsed.name);
    if (bucket === undefined) byName.set(parsed.name, [filePath]);
    else if (!bucket.includes(filePath)) bucket.push(filePath);
  }

  return [...byName.entries()]
    .filter(([, filePaths]) => filePaths.length > 1)
    .map(([name, filePaths]) => ({ name, filePaths: [...filePaths].sort((left, right) => left.localeCompare(right)) }))
    .sort((left, right) => left.name.localeCompare(right.name));
}

/**
 * Render the human/LLM-facing `MEMORY.md` from a built index. Deterministic:
 * kinds in `KIND_ORDER`, entries sorted by name, no timestamps.
 */
export function renderMemoryMarkdown(index: MemoryIndex, memoryDir: string): string {
  const lines: string[] = [
    MEMORY_MD_BANNER,
    '',
    '# Peaks Memory Index',
    '',
    '> Auto-generated by `peaks memory reindex`. Do not edit by hand — the next',
    '> reindex overwrites this file. Source of truth: `.peaks/memory/*.md`',
    '> (bodies) and `.peaks/memory/index.json` (machine index).',
    ''
  ];

  for (const kind of KIND_ORDER) {
    const entries = [...(index.hot[kind] ?? []), ...(index.warm[kind] ?? [])]
      .sort((left, right) => left.name.localeCompare(right.name));
    if (entries.length === 0) continue;
    lines.push(`## ${kind} (${entries.length})`, '');
    for (const entry of entries) {
      const link = relative(memoryDir, entry.sourcePath).replaceAll('\\', '/');
      lines.push(`- [${entry.name}](${link}) — ${entry.description}`);
    }
    lines.push('');
  }

  return lines.join('\n').replace(/\n+$/, '\n');
}

/**
 * Rebuild `.peaks/memory/index.json` from disk and (on `--apply`) regenerate
 * `MEMORY.md`. Always returns the drift report, even on a dry run.
 */
export function executeMemoryReindex(options: MemoryReindexOptions): MemoryReindexReport {
  const projectRoot = normalizeRoot(options.projectRoot);
  const apply = options.apply ?? false;
  const memoryDir = assertSafeProjectMemoryDir(projectRoot);
  const indexPath = join(memoryDir, 'index.json');
  const memoryMdPath = join(memoryDir, MEMORY_MD_FILENAME);

  const diskFiles = listMarkdownFiles(memoryDir).filter((filePath) => basename(filePath) !== MEMORY_MD_FILENAME);

  const orphanIndex = readPreviousIndexEntries(indexPath)
    .filter((entry) => typeof entry.sourcePath !== 'string' || entry.sourcePath.length === 0 || !existsSync(entry.sourcePath))
    .map((entry) => ({ name: entry.name, kind: entry.kind, sourcePath: entry.sourcePath }))
    .sort((left, right) => left.name.localeCompare(right.name));

  const unclassified = collectUnclassified(diskFiles);
  const nameConflicts = collectNameConflicts(diskFiles);

  // Build once; reuse for the write, the counts, and MEMORY.md so all three
  // views are guaranteed identical.
  const index = buildMemoryIndex(projectRoot);

  const writtenFiles: string[] = [];
  if (apply) {
    generateMemoryIndexFile(projectRoot, memoryDir, indexPath, index);
    writtenFiles.push(indexPath);
  }

  // Authoritative post-rebuild view: read the memories back through the same
  // read path every consumer uses, so `orphanDisk` is measured against the
  // real index rather than against this module's own scan.
  const memories = readProjectMemories(projectRoot);
  const indexedFilePaths = new Set(memories.memories.map((memory) => memory.filePath));
  const orphanDisk = diskFiles.filter((filePath) => !indexedFilePaths.has(filePath));

  const indexedByKind = emptyKindCounts();
  for (const memory of memories.memories) {
    indexedByKind[memory.kind] = (indexedByKind[memory.kind] ?? 0) + 1;
  }

  let memoryMdRegenerated = false;
  if (apply) {
    const markdown = renderMemoryMarkdown(index, memoryDir);
    // Plain write (not O_EXCL): MEMORY.md is a derived view and is expected
    // to be overwritten on every reindex.
    writeFileSync(memoryMdPath, markdown, 'utf8');
    writtenFiles.push(memoryMdPath);
    memoryMdRegenerated = true;
  }

  return {
    apply,
    projectRoot,
    memoryDir,
    indexPath,
    memoryMdPath,
    scannedFiles: diskFiles.length,
    indexed: memories.memories.length,
    indexedByKind,
    unclassified,
    nameConflicts,
    orphanIndex,
    orphanDisk,
    memoryMd: { path: memoryMdPath, regenerated: memoryMdRegenerated },
    writtenFiles
  };
}

