import type { CapabilityItem } from './recommendation-types.js';

export const seedCapabilityItems: CapabilityItem[] = [
  {
    capabilityId: 'everything-claude-code.code-review-agent',
    sourceId: 'everything-claude-code',
    name: 'Code Review Agent',
    itemType: 'agent',
    category: 'code-review',
    workflows: ['code-refactor', 'development-complete'],
    audience: ['engineer'],
    riskLevel: 'low',
    inputContract: 'git-diff or changed-file summary',
    outputContract: 'review-report',
    fallback: { mode: 'built-in-review-checklist', qualityImpact: 'lower', nextAction: 'Use Peaks built-in code review checklist if the external agent is unavailable.' },
    presentation: { displayName: { en: 'Code Review Agent', 'zh-CN': '代码评审代理' }, description: { en: 'Reviews code changes for quality, maintainability, tests, and risks.', 'zh-CN': '用于在代码改动后检查质量、可维护性、测试和风险。' } }
  },
  {
    capabilityId: 'everything-claude-code.security-review-agent',
    sourceId: 'everything-claude-code',
    name: 'Security Review Agent',
    itemType: 'agent',
    category: 'security-review',
    workflows: ['code-refactor', 'development-complete'],
    audience: ['engineer'],
    riskLevel: 'medium',
    inputContract: 'git-diff or changed-file summary',
    outputContract: 'security-review-report',
    fallback: { mode: 'built-in-security-checklist', qualityImpact: 'lower', nextAction: 'Use Peaks built-in security checklist if the external agent is unavailable.' },
    presentation: { displayName: { en: 'Security Review Agent', 'zh-CN': '安全评审代理' }, description: { en: 'Checks auth, user input, filesystem, external calls, and secret-handling risks.', 'zh-CN': '检查认证、用户输入、文件系统、外部调用和密钥处理风险。' } }
  },
  {
    capabilityId: 'everything-claude-code.language-standards',
    sourceId: 'everything-claude-code',
    name: 'Language Coding Standards',
    itemType: 'rule',
    category: 'coding-standards',
    workflows: ['code-refactor', 'development-start', 'project-standards'],
    audience: ['engineer'],
    riskLevel: 'low',
    inputContract: 'project-language and existing project standards',
    outputContract: 'project-local rules baseline',
    fallback: { mode: 'peaks-built-in-standards', qualityImpact: 'same', nextAction: 'Use Peaks curated baseline and preserve existing project conventions.' },
    presentation: { displayName: { en: 'Language Coding Standards', 'zh-CN': '语言编码规范' }, description: { en: 'Provides language coding standards for project-local Peaks rules.', 'zh-CN': '为项目内 Peaks 规则提供语言编码规范来源。' } }
  },
  {
    capabilityId: 'everything-claude-code.code-review-guidance',
    sourceId: 'everything-claude-code',
    name: 'Code Review Guidance',
    itemType: 'rule',
    category: 'code-review',
    workflows: ['code-refactor', 'development-complete', 'project-standards'],
    audience: ['engineer', 'qa'],
    riskLevel: 'low',
    inputContract: 'project-local diff and test evidence',
    outputContract: 'code-review rules baseline',
    fallback: { mode: 'peaks-built-in-review-checklist', qualityImpact: 'same', nextAction: 'Use Peaks curated code review baseline if the external source is unavailable.' },
    presentation: { displayName: { en: 'Code Review Guidance', 'zh-CN': '代码评审指导' }, description: { en: 'Provides review guidance for project-local Peaks rules and QA preflight.', 'zh-CN': '为项目内 Peaks 规则和 QA preflight 提供代码评审指导。' } }
  },
  {
    capabilityId: 'everything-claude-code.security-review-guidance',
    sourceId: 'everything-claude-code',
    name: 'Security Review Guidance',
    itemType: 'rule',
    category: 'security-review',
    workflows: ['code-refactor', 'development-complete', 'project-standards'],
    audience: ['engineer', 'qa'],
    riskLevel: 'low',
    inputContract: 'project-local diff and sensitive-boundary summary',
    outputContract: 'security-review rules baseline',
    fallback: { mode: 'peaks-built-in-security-checklist', qualityImpact: 'same', nextAction: 'Use Peaks curated security baseline if the external source is unavailable.' },
    presentation: { displayName: { en: 'Security Review Guidance', 'zh-CN': '安全评审指导' }, description: { en: 'Provides security review guidance for project-local Peaks rules and QA preflight.', 'zh-CN': '为项目内 Peaks 规则和 QA preflight 提供安全评审指导。' } }
  },
  {
    capabilityId: 'context7.docs-lookup',
    sourceId: 'context7',
    name: 'Context7 Docs Lookup',
    itemType: 'mcp',
    category: 'docs-lookup',
    workflows: ['code-refactor', 'product-refactor', 'frontend-design'],
    audience: ['engineer', 'product'],
    riskLevel: 'low',
    inputContract: 'library or API documentation request',
    outputContract: 'documentation-summary',
    fallback: { mode: 'manual-docs-input', qualityImpact: 'lower', nextAction: 'Ask the user to provide the relevant documentation link or pasted excerpt.' },
    presentation: { displayName: { en: 'Documentation Lookup', 'zh-CN': '文档查询能力' }, description: { en: 'Fetches current library and API documentation for implementation planning.', 'zh-CN': '用于获取当前库和 API 文档，辅助实现规划。' } }
  },
  capability('codegraph.project-indexing', 'codegraph', 'Codegraph Project Indexing', 'cli', 'project-analysis', ['engineer'], 'medium', 'peaks-rd-local-scan', 'Use Peaks RD local project scanning when codegraph is unavailable.', 'Codegraph Project Indexing', 'Codegraph 项目索引', 'Indexes a local project through the peaks codegraph execution boundary for role-skill analysis.', '通过 peaks codegraph 执行边界索引本地项目，辅助角色 skill 分析。'),
  capability('codegraph.semantic-query', 'codegraph', 'Codegraph Semantic Query', 'cli', 'project-analysis', ['engineer'], 'medium', 'peaks-rd-local-scan', 'Use local Grep/Glob and RD scanning when codegraph semantic query is unavailable.', 'Codegraph Semantic Query', 'Codegraph 语义查询', 'Queries local symbols and project relationships for RD planning evidence.', '查询本地符号和项目关系，为 RD 规划提供证据。'),
  capability('codegraph.impact-analysis', 'codegraph', 'Codegraph Impact Analysis', 'cli', 'impact-analysis', ['engineer', 'qa'], 'medium', 'peaks-rd-qa-impact-review', 'Use RD changed-file analysis and QA regression planning when codegraph affected output is unavailable.', 'Codegraph Impact Analysis', 'Codegraph 影响面分析', 'Analyzes likely impact for changed files so RD and QA can focus planning and regression scope.', '分析变更文件的可能影响面，帮助 RD 与 QA 聚焦规划和回归范围。'),
  capability('codegraph.context-pack', 'codegraph', 'Codegraph Context Pack', 'cli', 'context-pack', ['engineer', 'qa', 'product'], 'medium', 'peaks-txt-context-capsule', 'Use Peaks TXT context capsules and role-skill handoffs when codegraph context output is unavailable.', 'Codegraph Context Pack', 'Codegraph 上下文包', 'Builds task-specific local context that Code, RD, and TXT can use as supporting evidence.', '生成任务相关的本地上下文，作为 Code、RD 与 TXT 的辅助证据。'),
  capability('playwright-mcp.browser-validation', 'playwright-mcp', 'Playwright MCP Browser Validation', 'mcp', 'browser-validation', ['engineer', 'qa'], 'medium', 'manual-browser-test', 'Use local Playwright or manual browser verification.', 'Playwright Browser Validation', 'Playwright 浏览器验证', 'Validates UI flows through controlled browser automation.', '通过受控浏览器自动化验证 UI 流程。'),
  capability('chrome-devtools-mcp.browser-debug', 'chrome-devtools-mcp', 'Chrome DevTools Browser Debug', 'mcp', 'browser-debug', ['engineer', 'qa'], 'medium', 'manual-devtools-inspection', 'Use browser screenshots, console logs, and network traces supplied by the user.', 'Chrome DevTools Debug', 'Chrome DevTools 调试', 'Inspects runtime UI, console, network, and performance behavior.', '检查运行时 UI、控制台、网络和性能行为。'),
  capability('figma-context-mcp.design-context', 'figma-context-mcp', 'Figma Design Context', 'mcp', 'design-context', ['designer', 'engineer'], 'medium', 'manual-design-input', 'Ask the user for screenshots, tokens, or exported design notes.', 'Figma Design Context', 'Figma 设计上下文', 'Reads design context for UI implementation planning.', '读取设计上下文以辅助 UI 实现规划。'),
  capability('searchcode-mcp.code-search', 'searchcode-mcp', 'SearchCode MCP', 'mcp', 'code-search', ['engineer'], 'medium', 'local-code-search', 'Use local Grep/Glob and ask before sending private code externally.', 'External Code Search', '外部代码搜索', 'Searches code examples or repositories outside the current workspace.', '搜索当前工作区外部的代码示例或仓库。'),
  capability('mysql-mcp.database-inspection', 'mysql-mcp-server', 'MySQL Database Inspection', 'mcp', 'database-inspection', ['engineer'], 'high', 'schema-excerpt-input', 'Ask the user for schema excerpts or sanitized query plans.', 'MySQL Inspection', 'MySQL 检查', 'Inspects MySQL schema and data through an MCP boundary.', '通过 MCP 边界检查 MySQL schema 与数据。'),
  capability('agent-browser.browser-agent', 'agent-browser', 'Agent Browser', 'agent', 'browser-agent', ['engineer', 'qa'], 'medium', 'manual-browser-walkthrough', 'Use screenshots and manual test steps if agent browser is unavailable.', 'Agent Browser', '浏览器代理', 'Supports browser-based validation and interaction planning.', '支持基于浏览器的验证和交互规划。'),
  capability('claude-mem.memory-persistence', 'claude-mem', 'Claude Memory Persistence', 'skill', 'memory', ['engineer'], 'medium', 'peaks-txt-context-capsule', 'Use peaks-txt context capsules without storing secrets.', 'Memory Persistence', '记忆持久化', 'Persists reusable context when explicitly approved.', '在明确授权时持久化可复用上下文。'),
  capability('openspec.spec-workflow', 'openspec', 'OpenSpec Workflow', 'workflow', 'spec-workflow', ['product', 'engineer'], 'low', 'peaks-prd-rd-qa-artifacts', 'Use Peaks built-in PRD/RD/QA artifact flow.', 'OpenSpec Workflow', 'OpenSpec 规格流程', 'Supports spec-first product and engineering governance.', '支持规格优先的产品与工程治理。'),
  capability('gitnexus.repo-intelligence', 'gitnexus', 'GitNexus Repository Intelligence', 'cli', 'repo-intelligence', ['engineer'], 'medium', 'local-repo-scan', 'Use local project scanning through Peaks RD.', 'Repository Intelligence', '仓库智能分析', 'Repository intelligence should be proxied through Peaks before use.', '仓库智能分析应先通过 Peaks 代理边界再使用。'),
  capability('claude-code-best-practice.workflow-guidance', 'claude-code-best-practice', 'Claude Code Best Practice', 'doc', 'workflow-guidance', ['engineer'], 'low', 'peaks-built-in-rules', 'Use Peaks built-in workflow and review rules.', 'Claude Code Best Practice', 'Claude Code 最佳实践', 'Guidance for Claude Code engineering workflows.', 'Claude Code 工程工作流指导。'),
  capability('superpowers.workflow-methodology', 'superpowers', 'Superpowers Methodology', 'workflow', 'workflow-methodology', ['product', 'engineer'], 'low', 'peaks-workflow-route', 'Use Peaks route/autonomous plans.', 'Superpowers Methodology', 'Superpowers 方法论', 'Workflow and artifact methodology reference.', '工作流与 artifact 方法论参考。'),
  capability('understand-anything.knowledge-graph', 'understand-anything', 'Understand Anything Knowledge Graph', 'skill', 'project-analysis', ['engineer', 'product', 'qa'], 'low', 'peaks-codegraph-or-rd-scan', 'Use peaks codegraph or peaks RD project scan when Understand Anything is not installed. Optionally suggest installing it via Claude Code: /plugin marketplace add Lum1104/Understand-Anything then /plugin install understand-anything.', 'Understand Anything Knowledge Graph', 'Understand Anything 知识图谱', 'Multi-agent project knowledge graph that Peaks reads from .understand-anything/knowledge-graph.json when it has been generated by the Understand Anything plugin in Claude Code.', '通过 Claude Code 的 Understand Anything 插件生成的多 agent 知识图谱，Peaks 在 .understand-anything/knowledge-graph.json 存在时读取它作为项目分析证据。'),
  capability('penpot.design-source', 'penpot', 'Penpot Design Source', 'doc', 'design-source', ['designer', 'engineer'], 'medium', 'manual-design-input', 'Ask for exported design notes or screenshots.', 'Penpot Design Source', 'Penpot 设计来源', 'Design-source reference for UI planning.', '用于 UI 规划的设计来源参考。'),
  capability('gstack.product-stack-guidance', 'gstack', 'Product Stack Guidance', 'doc', 'product-guidance', ['product'], 'low', 'peaks-prd', 'Use peaks-prd for product goals and non-goals.', 'Product Stack Guidance', '产品栈指导', 'Product and startup stack guidance reference.', '产品与创业栈指导参考。'),
  capability('awesome-design-md.design-reference', 'awesome-design-md', 'Design Markdown Reference', 'doc', 'design-reference', ['designer', 'engineer'], 'low', 'peaks-ui-visual-direction', 'Use peaks-ui to define visual direction and interaction constraints.', 'Design Reference', '设计参考', 'Design markdown examples and inspiration.', '设计 markdown 示例与灵感。'),
  capability('reactbits.ui-reference', 'reactbits', 'React Bits UI Reference', 'doc', 'ui-reference', ['engineer', 'designer'], 'low', 'project-local-ui-patterns', 'Use project-local UI patterns and accessibility checks.', 'React UI Reference', 'React UI 参考', 'React UI and motion reference for frontend design.', 'React UI 与动效参考。'),
  capability('context-mode.context-management', 'context-mode', 'Context Management', 'mcp', 'context-management', ['engineer'], 'medium', 'peaks-txt-context-capsule', 'Use peaks-txt context capsules and avoid saving secrets.', 'Context Management', '上下文管理', 'Manages reusable context across workflows.', '管理跨工作流可复用上下文。'),
  capability('ruflo-access-repo.workflow-reference', 'ruflo-access-repo', 'Ruflo Workflow Reference', 'doc', 'workflow-reference', ['engineer'], 'medium', 'peaks-autonomous-planning', 'Use Peaks autonomous planning references without executing external code.', 'Workflow Reference', '工作流参考', 'Catalog-only workflow orchestration reference.', '仅作为目录化的工作流编排参考。'),
  capability('modelcontextprotocol-servers.collection', 'modelcontextprotocol-servers', 'MCP Server Collection', 'doc', 'mcp-collection', ['engineer'], 'medium', 'future-peaks-mcp-catalog', 'Use future Peaks MCP catalog review before selecting individual servers.', 'MCP Collection', 'MCP 集合', 'Catalog-only MCP server collection reference.', '仅作为目录化的 MCP server 集合参考。'),
  capability('andrej-karpathy-skills.guidance', 'andrej-karpathy-skills', 'Engineering Guidance', 'doc', 'engineering-guidance', ['engineer'], 'low', 'project-local-standards', 'Use project-local standards before external guidance.', 'Engineering Guidance', '工程指导', 'External engineering guidance reference.', '外部工程指导参考。'),
  capability('mattpocock-skills.product-prd-methods', 'mattpocock-skills', 'Product PRD Methods', 'skill', 'product-prd-methods', ['product', 'engineer'], 'low', 'peaks-prd', 'Use Peaks PRD artifacts first; inspect upstream to-prd, zoom-out, and grill-with-docs before applying method ideas.', 'Product PRD Methods', '产品 PRD 方法', 'References to-prd, zoom-out, and grill-with-docs for product shaping while Peaks PRD remains authoritative.', '参考 to-prd、zoom-out 和 grill-with-docs 进行产品塑形，Peaks PRD 仍保持权威。'),
  capability('mattpocock-skills.engineering-diagnosis', 'mattpocock-skills', 'Engineering Diagnosis Methods', 'skill', 'engineering-diagnosis', ['engineer'], 'low', 'peaks-rd', 'Use Peaks RD gates first; inspect upstream diagnose, triage, improve-codebase-architecture, and prototype before applying method ideas.', 'Engineering Diagnosis Methods', '工程诊断方法', 'References diagnosis, triage, architecture review, and prototype methods for RD analysis.', '为 RD 分析参考诊断、分流、架构评审和原型方法。'),
  capability('mattpocock-skills.tdd-method', 'mattpocock-skills', 'TDD Method', 'skill', 'tdd-method', ['engineer', 'qa'], 'low', 'peaks-rd-qa-gates', 'Use Peaks RD and QA test gates first; inspect upstream tdd before applying method ideas.', 'TDD Method', 'TDD 方法', 'References tests-first discipline for RD implementation and QA coverage review.', '为 RD 实现和 QA 覆盖评审参考测试先行纪律。'),
  capability('mattpocock-skills.qa-triage', 'mattpocock-skills', 'QA Triage Methods', 'skill', 'qa-triage', ['qa', 'engineer'], 'low', 'peaks-qa', 'Use Peaks QA validation gates first; inspect upstream triage and grill-with-docs before applying method ideas.', 'QA Triage Methods', 'QA 分流方法', 'References failure triage and document-backed acceptance checks for QA review.', '为 QA 评审参考失败分流和文档支撑的验收检查。'),
  capability('mattpocock-skills.handoff-context', 'mattpocock-skills', 'Handoff Context Methods', 'skill', 'handoff-context', ['product', 'engineer', 'qa'], 'low', 'peaks-txt-context-capsule', 'Use Peaks TXT local capsules first; inspect upstream handoff, to-issues, and write-a-skill before applying method ideas.', 'Handoff Context Methods', '交接上下文方法', 'References compact handoff, follow-up issue shaping, and reusable skill lesson capture for TXT.', '为 TXT 参考紧凑交接、后续 issue 塑形和可复用技能经验沉淀。'),
  capability('mattpocock-skills.git-guardrails', 'mattpocock-skills', 'Git Guardrails References', 'doc', 'git-guardrails', ['engineer'], 'medium', 'peaks-built-in-git-safety', 'Use Peaks and project-local git safety rules; do not install hooks or mutate git configuration automatically.', 'Git Guardrails References', 'Git 护栏参考', 'Catalog-only references for git guardrails and pre-commit setup; not an executable hook action.', 'Git 护栏和 pre-commit 设置的仅目录化参考；不是可执行 hook 动作。'),
  capability('impeccable.quality-guidance', 'impeccable', 'Quality Guidance', 'doc', 'quality-guidance', ['engineer'], 'low', 'peaks-review-gates', 'Use Peaks review gates as authoritative.', 'Quality Guidance', '质量指导', 'Quality reference catalog entry.', '质量参考目录项。'),
  capability('vercel-agent-skills.skill-pack', 'vercel-agent-skills', 'Vercel Agent Skills Pack', 'skill', 'skill-pack', ['engineer'], 'medium', 'external-skill-catalog', 'Inspect individual skills before use.', 'Agent Skills Pack', '代理技能包', 'Catalog-only external skill pack.', '仅作为目录化的外部技能包。'),
  capability('darwin-skill.external-skill', 'darwin-skill', 'Darwin Skill', 'skill', 'external-skill', ['engineer'], 'medium', 'external-skill-catalog', 'Inspect for project fit and safety before use.', 'Darwin Skill', 'Darwin 技能', 'Catalog-only external skill reference.', '仅作为目录化的外部技能参考。'),
  capability('taste-skill.design-critique', 'taste-skill', 'Design Critique', 'skill', 'design-critique', ['designer', 'engineer'], 'low', 'peaks-ui-constraints', 'Use Peaks UI constraints as authoritative.', 'Design Critique', '设计品味评审', 'External design critique reference.', '外部设计评审参考。'),
  capability('ui-ux-pro-max-skill.design-guidance', 'ui-ux-pro-max-skill', 'UI/UX Guidance', 'skill', 'design-guidance', ['designer', 'engineer'], 'medium', 'peaks-ui-constraints', 'Clarify product goals and accessibility constraints first.', 'UI/UX Guidance', 'UI/UX 指导', 'External UI/UX guidance reference.', '外部 UI/UX 指导参考。'),
  capability('ruflo-mcp-server.workflow-reference', 'ruflo-mcp-server', 'Ruflo Workflow Reference', 'doc', 'workflow-reference', ['engineer'], 'medium', 'peaks-autonomous-planning', 'Use as orchestration inspiration only.', 'Workflow Reference', '工作流参考', 'Catalog-only workflow orchestration reference.', '仅作为目录化的工作流编排参考。'),
  capability('anthropic-skills.skill-pack', 'anthropic-skills', 'Anthropic Skills Pack', 'skill', 'skill-pack', ['engineer'], 'medium', 'external-skill-catalog', 'Inspect individual skills before use.', 'Skills Pack', '技能包', 'Catalog-only external skill pack.', '仅作为目录化的外部技能包。'),
  capability('vercel-skills.skill-pack', 'vercel-skills', 'Vercel Skills Pack', 'skill', 'skill-pack', ['engineer'], 'medium', 'external-skill-catalog', 'Inspect individual skills before use.', 'Skills Pack', '技能包', 'Catalog-only external skill pack.', '仅作为目录化的外部技能包。'),
  capability('azure-skills.cloud-skill-pack', 'azure-skills', 'Azure Skills Pack', 'skill', 'cloud-skill-pack', ['engineer'], 'high', 'cloud-capability-catalog', 'Require explicit confirmation and credentials for cloud actions.', 'Azure Skills Pack', 'Azure 技能包', 'Catalog-only cloud skill pack.', '仅作为目录化的云技能包。')
];

function capability(
  capabilityId: string,
  sourceId: string,
  name: string,
  itemType: CapabilityItem['itemType'],
  category: string,
  audience: string[],
  riskLevel: CapabilityItem['riskLevel'],
  fallbackMode: string,
  nextAction: string,
  displayNameEn: string,
  displayNameZh: string,
  descriptionEn: string,
  descriptionZh: string
): CapabilityItem {
  return {
    capabilityId,
    sourceId,
    name,
    itemType,
    category,
    workflows: ['capability-map'],
    audience,
    riskLevel,
    fallback: { mode: fallbackMode, qualityImpact: fallbackMode.startsWith('peaks-') ? 'same' : 'lower', nextAction },
    presentation: { displayName: { en: displayNameEn, 'zh-CN': displayNameZh }, description: { en: descriptionEn, 'zh-CN': descriptionZh } }
  };
}
