/**
 * Template-integrity guard — slice 2026-07-15-project-scan-bootstrap (R4).
 *
 * The 4 audit/business templates bundled at
 * `src/services/workspace/templates/project-scan/*.md` MUST match
 * byte-for-byte the canonical sources at `.peaks/project-scan/{4 files}`.
 * Any drift between the bundled copies and the canonical sources is
 * a regression: the bootstrap service would propagate stale templates
 * to every consumer project on `peaks workspace init`.
 *
 * This test enforces 0-byte drift. The mechanism is intentionally
 * mechanical (file equality) — we do NOT parse YAML or frontmatter,
 * because the goal is "what gets copied is exactly what's in the
 * canonical source", not "the schemas are consistent" (the schema
 * drift test is owned by `services/prd/project-scan-sediment.test.ts`).
 */
import { readFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { TEMPLATE_FILES } from '../../../../src/services/workspace/templates/project-scan/index.js';

const here = dirname(fileURLToPath(import.meta.url));
// tests/unit/workspace/templates/ → repo root (4 levels up)
const REPO_ROOT = resolve(here, '..', '..', '..', '..');

const BUNDLED_DIR = join(
  REPO_ROOT,
  'src',
  'services',
  'workspace',
  'templates',
  'project-scan'
);
const CANONICAL_DIR = join(REPO_ROOT, '.peaks', 'project-scan');

describe('bundled project-scan templates match canonical sources (slice 2026-07-15-project-scan-bootstrap, R4)', () => {
  for (const name of TEMPLATE_FILES) {
    it(`${name} — bundled copy is byte-equal to canonical source`, () => {
      const bundledPath = join(BUNDLED_DIR, name);
      const canonicalPath = join(CANONICAL_DIR, name);

      // Both files MUST exist. A missing file is a hard regression:
      // the bootstrap service cannot copy what isn't there.
      expect(
        statSync(bundledPath, { throwIfNoEntry: false }),
        `bundled template missing at ${bundledPath}`
      ).toBeTruthy();
      expect(
        statSync(canonicalPath, { throwIfNoEntry: false }),
        `canonical template missing at ${canonicalPath}`
      ).toBeTruthy();

      const bundledBytes = readFileSync(bundledPath);
      const canonicalBytes = readFileSync(canonicalPath);

      // 0-byte drift — surface a clear failure message when the bytes
      // diverge. Buffer.equals is constant-time for equal-length buffers;
      // length mismatch produces the diff hint via the message below.
      if (bundledBytes.length !== canonicalBytes.length) {
        throw new Error(
          `template drift: ${name} size differs — ` +
            `bundled=${bundledBytes.length} canonical=${canonicalBytes.length}. ` +
            `Re-copy the canonical source from ${canonicalPath} to ${bundledPath}.`
        );
      }
      expect(
        bundledBytes.equals(canonicalBytes),
        `template drift: ${name} content differs between bundled and canonical copies. ` +
          `Diff them and re-copy from ${canonicalPath} to ${bundledPath}.`
      ).toBe(true);
    });
  }

  it('TEMPLATE_FILES does not include project-scan.md (that file is dynamic)', () => {
    // Slice 2026-07-15-project-scan-bootstrap design: project-scan.md is
    // generated by bootstrapProjectScan from archetype/libraries scan
    // output. It is NOT a static template, so it MUST NOT appear in
    // TEMPLATE_FILES.
    expect(TEMPLATE_FILES as readonly string[]).not.toContain('project-scan.md');
  });
});