// Auto-generated by peaks-rd seam cleanup (slice-c followup, 2026-07-06)
// Re-exports dirSizeMb for testing only — keep prod src clean per PRD.
// Prod src attaches dirSizeMb as a non-enumerable property on
// collectResourceSnapshot (NOT a module-level export), so the shim
// reaches it via that property. This keeps Object.keys of the module
// free of "dirSizeMb" while still allowing AC-1/AC-2/AC-3/AC-6
// unit tests to drive the function directly.
import { collectResourceSnapshot } from '../../src/snapshot.js';
export const dirSizeMb = (collectResourceSnapshot as unknown as {
  dirSizeMb: (dir: string, opts?: { maxEntries?: number }) => number;
}).dirSizeMb;