/**
 * Slice 2026-06-14-cc-connect-weixin (slice 3 + change-1) — `~/.cc-connect/config.toml`
 * template generator. The template contains only the weixin platform
 * block per the PRD's AC2. We do NOT include feishu / slack /
 * discord / wecom / qq / line / telegram / etc. — the slice is
 * weixin-only.
 *
 * The generated TOML is consumed directly by `cc-connect` (Go). It
 * has no JSON5 / YAML / HOCON variants — TOML is the only config
 * format cc-connect understands.
 *
 * The schema MUST match what `cc-connect` parses (see BUG 6 — fix
 * 2026-06-14-cc-connect-weixin#6). cc-connect's Go config struct
 * decodes `projects` as `[]Project`, so the TOML must use
 * `[[projects]]` (array of tables), not `[projects]` (single
 * map). Each project entry binds an agent block
 * (`[projects.agent]` + `[projects.agent.options]`) to one or more
 * platform blocks (`[[projects.platforms]]` +
 * `[projects.platforms.options]`).
 *
 * Change-1: peaks config is now the source of truth; the renderer
 * takes a typed `CompanionConfig` (from `~/.peaks/config.json`) and
 * derives the TOML from it. When `enabled === false`, the rendered
 * TOML has no `[[projects.platforms]]` block (empty body). When
 * `defaultChannel !== 'weixin'` we throw a typed error (peaks
 * config is malformed; we're strict here).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { DEFAULT_COMPANION_CHANNEL } from './companion-types.js';
import type { CompanionConfig } from '../config/config-types.js';

export const CC_CONNECT_CONFIG_FILENAME = 'config.toml';
export const CC_CONNECT_CONFIG_HEADER = [
  '# cc-connect configuration',
  '# Generated by `peaks companion setup` (slice 2026-06-14-cc-connect-weixin).',
  '# Source of truth: ~/.peaks/config.json#companion (slim 2.0 schema).',
  '# Edits are preserved across regenerations; do not add non-weixin platform',
  '# blocks here while the peaks-cli slice is weixin-only.',
  ''
].join('\n');

export function ccConnectConfigDir(home: string = homedir()): string {
  return join(home, '.cc-connect');
}

export function ccConnectConfigFile(home: string = homedir()): string {
  return join(ccConnectConfigDir(home), CC_CONNECT_CONFIG_FILENAME);
}

export type WeixinPlatformOptions = {
  /** Project name (required by cc-connect). Defaults to "default". */
  projectName?: string;
  /** Optional allow-list of WeChat user IDs. */
  allowFrom?: string;
};

/**
 * Thin input shape accepted by `renderWeixinConfig` when called
 * outside the typed-peaks-config flow (e.g. legacy tests, CLI
 * overrides). The full slice change-1 path goes through
 * `renderCompanionConfig` (typed `CompanionConfig`).
 *
 * `agentType` overrides the default agent type (`"claudecode"`).
 * `agentWorkDir` overrides the default `work_dir`
 * (`process.cwd()`) for `[projects.agent.options]`.
 * `longPollTimeoutMs` (when set) is emitted as
 * `[projects.platforms.options].long_poll_timeout_ms`.
 */
export type RenderConfigInput = {
  channel?: 'weixin';
  projectName?: string;
  allowFrom?: string;
  agentType?: string;
  agentWorkDir?: string;
  longPollTimeoutMs?: number;
};

const DEFAULT_PROJECT_NAME = 'default';
/** Canonical agent type for AI-agent-on-WeChat (see BUG 6 fix). */
export const DEFAULT_AGENT_TYPE = 'claudecode';
/** Canonical agent permission mode (see cc-connect example config). */
export const DEFAULT_AGENT_MODE = 'default';

/**
 * Extract the project name (the `name = "..."` field) from a
 * iLink-style QR payload like `ilink://peaks-cli?project=default`.
 * Falls back to `"default"` when the payload doesn't carry a
 * `project=` parameter or when it's not a string.
 */
export function projectNameFromIlinkQrPayload(payload: string | undefined | null): string {
  if (typeof payload !== 'string' || payload.length === 0) return DEFAULT_PROJECT_NAME;
  const match = /[?&]project=([^&]+)/.exec(payload);
  if (match === null || match[1] === undefined) return DEFAULT_PROJECT_NAME;
  let raw = match[1];
  try {
    raw = decodeURIComponent(raw);
  } catch {
    /* fall through with raw value */
  }
  const trimmed = raw.trim();
  return trimmed.length > 0 ? trimmed : DEFAULT_PROJECT_NAME;
}

/**
 * Typed-renderer entry point. Takes the canonical `CompanionConfig`
 * block from `~/.peaks/config.json` and produces the weixin-only
 * TOML body.
 *
 * Behaviors:
 *   - `enabled === false`: returns an empty body (no platforms block).
 *   - `defaultChannel !== 'weixin'`: throws a typed error (strict;
 *     peaks config is malformed if a non-weixin channel ever lands
 *     here while the slice is weixin-only).
 */
export function renderCompanionConfig(config: CompanionConfig): string {
  if (config.defaultChannel !== 'weixin') {
    throw new CompanionConfigError(
      `companion.defaultChannel="${config.defaultChannel}" is not supported in this slice; only "weixin" is wired (slice 2026-06-14-cc-connect-weixin)`
    );
  }
  if (config.enabled !== true) {
    return `${CC_CONNECT_CONFIG_HEADER.trimEnd()}\n# companion.enabled=false; cc-connect will not be started until you opt in.\n`;
  }
  const projectName = projectNameFromIlinkQrPayload(config.weixin.ilinkQrPayload);
  return renderWeixinConfig({
    channel: 'weixin',
    projectName,
    ...(config.agentType !== undefined ? { agentType: config.agentType } : {}),
    ...(config.agentWorkDir !== undefined ? { agentWorkDir: config.agentWorkDir } : {})
  });
}

/** Typed error for malformed peaks companion config. */
export class CompanionConfigError extends Error {
  public readonly code = 'COMPANION_CONFIG_INVALID';
  constructor(message: string) {
    super(message);
    this.name = 'CompanionConfigError';
  }
}

/**
 * Render the weixin-only TOML config body. Returns the full file
 * contents. We always emit a single `[[projects]]` entry (array of
 * tables — required by cc-connect's Go config decoder, BUG 6 fix)
 * bound to a `[projects.agent]` + `[projects.agent.options]`
 * block (claudecode by default) and a single
 * `[[projects.platforms]]` of type weixin. No other platform types
 * are emitted (PRD: AC2 / AC6).
 *
 * Schema reference (canonical, see `cc-connect config example`):
 *
 *     [[projects]]
 *     name = "<projectName>"
 *
 *     [projects.agent]
 *     type = "claudecode"
 *
 *     [projects.agent.options]
 *     work_dir = "<cwd or peaks work dir>"
 *     mode = "default"
 *
 *     [[projects.platforms]]
 *     type = "weixin"
 *
 *     [projects.platforms.options]
 *     allow_from = "*" | "<comma-separated user ids>"
 *     account_id = "<projectName>"
 *     # long_poll_timeout_ms = 35000
 */
export function renderWeixinConfig(input: RenderConfigInput = {}): string {
  const channel = input.channel ?? DEFAULT_COMPANION_CHANNEL;
  if (channel !== 'weixin') {
    throw new Error(`channel not supported in this slice: ${channel}`);
  }
  const projectName = input.projectName?.trim() || DEFAULT_PROJECT_NAME;
  const allowFrom = input.allowFrom?.trim();
  const agentType = input.agentType?.trim() || DEFAULT_AGENT_TYPE;
  const agentWorkDir = input.agentWorkDir?.trim() || process.cwd();
  const longPollTimeoutMs = input.longPollTimeoutMs;

  const lines: string[] = [
    CC_CONNECT_CONFIG_HEADER.trimEnd(),
    '',
    '[[projects]]',
    `name = "${projectName}"`,
    '',
    '[projects.agent]',
    `type = "${agentType}"`,
    '',
    '[projects.agent.options]',
    `work_dir = "${agentWorkDir}"`,
    `mode = "${DEFAULT_AGENT_MODE}"`,
    '',
    '[[projects.platforms]]',
    'type = "weixin"',
    '',
    '[projects.platforms.options]',
    '# token is filled in by `cc-connect weixin setup` after the user scans the QR',
    '# base_url defaults to the public ilink gateway when omitted',
    `account_id = "${projectName}"`,
    '# long_poll_timeout_ms = 35000'
  ];
  if (longPollTimeoutMs !== undefined && Number.isFinite(longPollTimeoutMs) && longPollTimeoutMs > 0) {
    lines.push(`long_poll_timeout_ms = ${Math.floor(longPollTimeoutMs)}`);
  }
  if (allowFrom !== undefined && allowFrom.length > 0) {
    lines.push(`allow_from = "${allowFrom}"`);
  } else {
    // Default to "*" so the user's first scan isn't blocked (matches
    // the canonical example). Tests can still assert against this.
    lines.push('allow_from = "*"');
  }
  return lines.join('\n') + '\n';
}

export type WriteConfigResult = {
  ok: boolean;
  path: string;
  error: string | null;
  /** True when the file already existed and we preserved it. */
  preserved: boolean;
};

/**
 * Write the config file. If the file already exists and `overwrite`
 * is false, return `preserved: true` without modifying the file
 * (this is the default; matches AC7: "do not write config.toml
 * before the user confirms"). If `overwrite` is true, replace the
 * file (used after the user accepts the prompt).
 */
export function writeCcConnectConfig(
  body: string,
  options: { home?: string; overwrite?: boolean } = {}
): WriteConfigResult {
  const home = options.home ?? homedir();
  const file = ccConnectConfigFile(home);
  try {
    if (existsSync(file) && options.overwrite !== true) {
      return { ok: true, path: file, error: null, preserved: true };
    }
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, body, 'utf8');
    return { ok: true, path: file, error: null, preserved: false };
  } catch (err) {
    return { ok: false, path: file, error: err instanceof Error ? err.message : String(err), preserved: false };
  }
}

/** Read the existing config (used for diff prompting in slice-3+). */
export function readCcConnectConfig(home: string = homedir()): { body: string; mtimeMs: number | null; path: string } | null {
  const file = ccConnectConfigFile(home);
  if (!existsSync(file)) return null;
  let mtimeMs: number | null = null;
  try {
    mtimeMs = statSync(file).mtimeMs;
  } catch {
    mtimeMs = null;
  }
  return { body: readFileSync(file, 'utf8'), mtimeMs, path: file };
}

/**
 * Cheap channel check: scan a TOML body for non-weixin platform
 * types. Returns the list of unsupported platform types found
 * (empty when the file is weixin-only or absent). Used by the
 * setup service to warn the user before overwriting an
 * existing config that has feishu / slack / etc.
 *
 * Scope: only inspects `type = "..."` lines that appear after an
 * `[[projects.platforms]]` array-of-tables header. This avoids
 * false positives from `[projects.agent]\ntype = "claudecode"`
 * (BUG 6 fix).
 */
export function detectNonWeixinPlatforms(toml: string): string[] {
  const out = new Set<string>();
  const lines = toml.split(/\r?\n/);
  let inPlatformsBlock = false;
  for (const line of lines) {
    // Track block boundaries. We re-enter "platforms" mode on every
    // `[[projects.platforms]]` marker, and exit when we see a new
    // top-level `[[...]]` or `[...]` block.
    if (/^\s*\[\[projects\.platforms\]\]\s*$/.test(line)) {
      inPlatformsBlock = true;
      continue;
    }
    if (/^\s*(\[\[|\[)[^\]]*(\]\]|\])\s*$/.test(line)) {
      // Any other table/array-of-tables header — leave platforms scope.
      inPlatformsBlock = false;
      continue;
    }
    if (!inPlatformsBlock) continue;
    const m = /^\s*type\s*=\s*"([^"]+)"\s*$/.exec(line);
    if (m && m[1] && m[1] !== 'weixin') {
      out.add(m[1]);
    }
  }
  return [...out];
}
