/**
 * Slice 2026-06-14-cc-connect-weixin (slice 3) — `~/.cc-connect/config.toml`
 * template generator. The template contains only the weixin platform
 * block per the PRD's AC2. We do NOT include feishu / slack /
 * discord / wecom / qq / line / telegram / etc. — the slice is
 * weixin-only.
 *
 * The generated TOML is consumed directly by `cc-connect` (Go). It
 * has no JSON5 / YAML / HOCON variants — TOML is the only config
 * format cc-connect understands.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { DEFAULT_COMPANION_CHANNEL } from './companion-types.js';

export const CC_CONNECT_CONFIG_FILENAME = 'config.toml';
export const CC_CONNECT_CONFIG_HEADER = [
  '# cc-connect configuration',
  '# Generated by `peaks companion setup` (slice 2026-06-14-cc-connect-weixin).',
  '# Edits are preserved across regenerations; do not add non-weixin platform',
  '# blocks here while the peaks-cli slice is weixin-only.',
  ''
].join('\n');

export function ccConnectConfigDir(home: string = homedir()): string {
  return join(home, '.cc-connect');
}

export function ccConnectConfigFile(home: string = homedir()): string {
  return join(ccConnectConfigDir(home), CC_CONNECT_CONFIG_FILENAME);
}

export type WeixinPlatformOptions = {
  /** Project name (required by cc-connect). Defaults to "default". */
  projectName?: string;
  /** Optional allow-list of WeChat user IDs. */
  allowFrom?: string;
};

export type RenderConfigInput = {
  channel?: 'weixin';
  projectName?: string;
  allowFrom?: string;
};

const DEFAULT_PROJECT_NAME = 'default';

/**
 * Render the weixin-only TOML config body. Returns the full file
 * contents. We always emit the `[projects]` block + a single
 * `[[projects.platforms]]` of type weixin. No other platform types
 * are emitted (PRD: AC2 / AC6).
 */
export function renderWeixinConfig(input: RenderConfigInput = {}): string {
  const channel = input.channel ?? DEFAULT_COMPANION_CHANNEL;
  if (channel !== 'weixin') {
    throw new Error(`channel not supported in this slice: ${channel}`);
  }
  const projectName = input.projectName?.trim() || DEFAULT_PROJECT_NAME;
  const allowFrom = input.allowFrom?.trim();
  const lines: string[] = [
    CC_CONNECT_CONFIG_HEADER.trimEnd(),
    '',
    '[projects]',
    `name = "${projectName}"`,
    '',
    '[[projects.platforms]]',
    'type = "weixin"',
    '',
    '[projects.platforms.options]',
    '# token is filled in by `cc-connect weixin setup` after the user scans the QR',
    '# base_url defaults to the public ilink gateway when omitted',
    `# account_id = "${projectName}"`,
    '# long_poll_timeout_ms = 35000',
  ];
  if (allowFrom !== undefined && allowFrom.length > 0) {
    lines.push(`allow_from = "${allowFrom}"`);
  }
  return lines.join('\n') + '\n';
}

export type WriteConfigResult = {
  ok: boolean;
  path: string;
  error: string | null;
  /** True when the file already existed and we preserved it. */
  preserved: boolean;
};

/**
 * Write the config file. If the file already exists and `overwrite`
 * is false, return `preserved: true` without modifying the file
 * (this is the default; matches AC7: "do not write config.toml
 * before the user confirms"). If `overwrite` is true, replace the
 * file (used after the user accepts the prompt).
 */
export function writeCcConnectConfig(
  body: string,
  options: { home?: string; overwrite?: boolean } = {}
): WriteConfigResult {
  const home = options.home ?? homedir();
  const file = ccConnectConfigFile(home);
  try {
    if (existsSync(file) && options.overwrite !== true) {
      return { ok: true, path: file, error: null, preserved: true };
    }
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, body, 'utf8');
    return { ok: true, path: file, error: null, preserved: false };
  } catch (err) {
    return { ok: false, path: file, error: err instanceof Error ? err.message : String(err), preserved: false };
  }
}

/** Read the existing config (used for diff prompting in slice-3+). */
export function readCcConnectConfig(home: string = homedir()): { body: string; mtimeMs: number | null; path: string } | null {
  const file = ccConnectConfigFile(home);
  if (!existsSync(file)) return null;
  let mtimeMs: number | null = null;
  try {
    mtimeMs = statSync(file).mtimeMs;
  } catch {
    mtimeMs = null;
  }
  return { body: readFileSync(file, 'utf8'), mtimeMs, path: file };
}

/**
 * Cheap channel check: scan a TOML body for non-weixin platform
 * types. Returns the list of unsupported platform types found
 * (empty when the file is weixin-only or absent). Used by the
 * setup service to warn the user before overwriting an
 * existing config that has feishu / slack / etc.
 */
export function detectNonWeixinPlatforms(toml: string): string[] {
  const out = new Set<string>();
  const lines = toml.split(/\r?\n/);
  for (const line of lines) {
    const m = /^\s*type\s*=\s*"([^"]+)"\s*$/.exec(line);
    if (m && m[1] && m[1] !== 'weixin') {
      out.add(m[1]);
    }
  }
  return [...out];
}
