// tests/unit/services/memory/memory-rotate.test.ts
//
// Unit tests for `peaks memory rotate` (slice
// 2026-09-10-memory-vocab-and-rotate, F).
//
// Pins the mandatory safety gates:
//   1. dry-run by default — nothing moves without --apply
//   2. tier A/B are never selected (rules, conventions, pinned files)
//   3. the reference grep excludes any candidate mentioned in src/ + skills/
//   4. tier D is report-only — never deleted, even with --apply
//   5. --apply refuses an empty plan or an unverifiable reference root
//   6. 6-month retention (user override of the policy's 12 months)
//
// Run with:
//   pnpm vitest run tests/unit/services/memory/memory-rotate.test.ts

import { existsSync, mkdirSync, mkdtempSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  executeMemoryRotate,
  MEMORY_ROTATION_RETENTION_MONTHS,
  readExplicitTier
} from '~/src/services/memory/memory-rotate-service';

const NOW = new Date('2026-09-10T00:00:00.000Z');
/** Well outside the 6-month window (cutoff ≈ 2026-03-10). */
const OLD_DATE = '2025-01-01';
/** Inside the window. */
const RECENT_DATE = '2026-08-01';

let root: string;
let memoryDir: string;
let archivedDir: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'peaks-rotate-'));
  memoryDir = join(root, '.peaks', 'memory');
  archivedDir = join(memoryDir, 'archived');
  mkdirSync(memoryDir, { recursive: true });
  // The reference-grep gate refuses --apply when a root is missing.
  mkdirSync(join(root, 'src'), { recursive: true });
  mkdirSync(join(root, 'skills'), { recursive: true });
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

function writeMemory(fileName: string, frontmatterLines: readonly string[], body = 'Body text.'): string {
  const filePath = join(memoryDir, fileName);
  writeFileSync(filePath, ['---', ...frontmatterLines, '---', '', body, ''].join('\n'), 'utf8');
  return filePath;
}

function frontmatter(name: string, kind: string, extra: readonly string[] = []): string[] {
  return [`name: ${name}`, `description: ${name}`, 'metadata:', `  type: ${kind}`, ...extra];
}

describe('executeMemoryRotate — planning', () => {
  it('dry-run reports tier-C archive candidates without moving anything', () => {
    const filePath = writeMemory('old-lesson.md', frontmatter('old-lesson', 'lesson', [`  updatedAt: ${OLD_DATE}`]));

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.apply).toBe(false);
    expect(report.retentionMonths).toBe(6);
    expect(MEMORY_ROTATION_RETENTION_MONTHS).toBe(6);
    expect(report.tierCounts.C).toBe(1);
    expect(report.candidates).toHaveLength(1);
    expect(report.candidates[0]!.action).toBe('archive');
    expect(report.candidates[0]!.ageBasis).toBe('frontmatter');
    expect(report.archived).toEqual([]);
    expect(existsSync(filePath)).toBe(true);
  });

  it('leaves tier-C files inside the 6-month window alone', () => {
    writeMemory('recent-lesson.md', frontmatter('recent-lesson', 'lesson', [`  updatedAt: ${RECENT_DATE}`]));

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.candidates).toHaveLength(0);
    expect(report.tierCounts.C).toBe(1);
  });

  it('never selects tier A or tier B, even when old', () => {
    writeMemory('old-rule.md', frontmatter('old-rule', 'rule', [`  updatedAt: ${OLD_DATE}`]));
    writeMemory('old-convention.md', frontmatter('old-convention', 'convention', [`  updatedAt: ${OLD_DATE}`]));
    writeMemory('old-feedback.md', frontmatter('old-feedback', 'feedback', [`  updatedAt: ${OLD_DATE}`]));

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.tierCounts.A).toBe(2);
    expect(report.tierCounts.B).toBe(1);
    expect(report.candidates).toHaveLength(0);
    for (const candidate of report.candidates) {
      expect(['A', 'B']).not.toContain(candidate.tier);
    }
  });

  it('treats a file pinned in MEMORY.md as tier B and excludes it', () => {
    writeMemory('pinned-lesson.md', frontmatter('pinned-lesson', 'lesson', [`  updatedAt: ${OLD_DATE}`]));
    writeFileSync(join(memoryDir, 'MEMORY.md'), [
      '<!-- generated by `peaks memory reindex` — do not edit -->',
      '- [pinned-lesson](pinned-lesson.md) — pinned entry'
    ].join('\n'), 'utf8');

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.tierCounts.B).toBe(1);
    expect(report.candidates).toHaveLength(0);
    expect(report.excluded.map((entry) => entry.reason)).toContain('pinned in MEMORY.md index');
  });

  it('reports tier-D files as delete-candidates only', () => {
    mkdirSync(archivedDir, { recursive: true });
    writeFileSync(join(archivedDir, 'old-scratch.md'), [
      '---', 'name: old-scratch', 'description: old-scratch', 'metadata:', '  type: project', '---', '', 'Body.', ''
    ].join('\n'), 'utf8');

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.tierCounts.D).toBe(1);
    expect(report.candidates).toHaveLength(1);
    expect(report.candidates[0]!.action).toBe('delete-candidate');
    expect(report.candidates[0]!.tier).toBe('D');
  });

  it('honours an explicit metadata.tier over the kind heuristic', () => {
    writeMemory('explicit-d.md', frontmatter('explicit-d', 'rule', [`  updatedAt: ${OLD_DATE}`, '  tier: D']));

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.tierCounts.D).toBe(1);
    expect(report.candidates[0]!.action).toBe('delete-candidate');
    expect(report.candidates[0]!.tierReason).toContain('explicit metadata.tier: D');
  });

  it('excludes a candidate referenced from src/ or skills/', () => {
    writeMemory('referenced-lesson.md', frontmatter('referenced-lesson', 'lesson', [`  updatedAt: ${OLD_DATE}`]));
    writeFileSync(join(root, 'src', 'consumer.ts'), 'export const MEMORY = "referenced-lesson";\n', 'utf8');

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.candidates).toHaveLength(0);
    expect(report.excluded).toHaveLength(1);
    expect(report.excluded[0]!.reason).toContain('src/consumer.ts');
  });

  it('uses file mtime when the frontmatter carries no date', () => {
    const filePath = writeMemory('mtime-lesson.md', frontmatter('mtime-lesson', 'lesson'));
    const old = new Date('2025-01-01T00:00:00.000Z');
    utimesSync(filePath, old, old);

    const report = executeMemoryRotate({ projectRoot: root, apply: false, now: NOW });

    expect(report.candidates).toHaveLength(1);
    expect(report.candidates[0]!.ageBasis).toBe('mtime');
  });
});

describe('executeMemoryRotate — apply', () => {
  it('archives a tier-C candidate into archived/', () => {
    const filePath = writeMemory('old-lesson.md', frontmatter('old-lesson', 'lesson', [`  updatedAt: ${OLD_DATE}`]));

    const report = executeMemoryRotate({ projectRoot: root, apply: true, now: NOW });

    expect(report.refused).toBe(false);
    expect(report.archived).toHaveLength(1);
    expect(report.archived[0]).toBe(join(archivedDir, 'old-lesson.md'));
    expect(existsSync(filePath)).toBe(false);
    expect(existsSync(join(archivedDir, 'old-lesson.md'))).toBe(true);
  });

  it('never deletes a tier-D file, even with --apply', () => {
    mkdirSync(archivedDir, { recursive: true });
    const filePath = join(archivedDir, 'old-scratch.md');
    writeFileSync(filePath, [
      '---', 'name: old-scratch', 'description: old-scratch', 'metadata:', '  type: project', '---', '', 'Body.', ''
    ].join('\n'), 'utf8');

    const report = executeMemoryRotate({ projectRoot: root, apply: true, now: NOW });

    expect(report.candidates[0]!.action).toBe('delete-candidate');
    expect(report.archived).toEqual([]);
    expect(existsSync(filePath)).toBe(true);
  });

  it('refuses to apply an empty plan', () => {
    const report = executeMemoryRotate({ projectRoot: root, apply: true, now: NOW });

    expect(report.candidates).toHaveLength(0);
    expect(report.refused).toBe(true);
    expect(report.refusalReasons.join(' ')).toContain('no rotation candidates');
    expect(existsSync(archivedDir)).toBe(false);
  });

  it('refuses to apply when a reference-grep root is missing', () => {
    writeMemory('old-lesson.md', frontmatter('old-lesson', 'lesson', [`  updatedAt: ${OLD_DATE}`]));
    rmSync(join(root, 'skills'), { recursive: true, force: true });

    const report = executeMemoryRotate({ projectRoot: root, apply: true, now: NOW });

    expect(report.gateFailures.join(' ')).toContain('reference-grep root not found');
    expect(report.refused).toBe(true);
    expect(report.archived).toEqual([]);
    expect(existsSync(join(memoryDir, 'old-lesson.md'))).toBe(true);
  });

  it('does not overwrite an existing archive file', () => {
    const filePath = writeMemory('old-lesson.md', frontmatter('old-lesson', 'lesson', [`  updatedAt: ${OLD_DATE}`]));
    mkdirSync(archivedDir, { recursive: true });
    const destination = join(archivedDir, 'old-lesson.md');
    writeFileSync(destination, 'existing archive content\n', 'utf8');

    const report = executeMemoryRotate({ projectRoot: root, apply: true, now: NOW });

    expect(report.archived).toEqual([]);
    expect(existsSync(filePath)).toBe(true);
    expect(report.excluded.map((entry) => entry.reason).join(' ')).toContain('archive destination already exists');
  });
});

describe('readExplicitTier', () => {
  it('reads nested and top-level tier values case-insensitively', () => {
    expect(readExplicitTier('metadata:\n  tier: a')).toBe('A');
    expect(readExplicitTier('tier: C\nname: x')).toBe('C');
    expect(readExplicitTier('name: x\nmetadata:\n  type: rule')).toBeNull();
    expect(readExplicitTier('metadata:\n  tier: X')).toBeNull();
  });
});
