/**
 * Slice 2026-06-26-audit-artifact-writer-generalization — forward-looking
 * shape guard for `.peaks/memory/`.
 *
 * Background: peaks-loop publishes a memory contract — files under
 * `.peaks/memory/` should follow one of three shapes:
 *
 *   (a) `index.json` — the memory index, regenerated by the memory service.
 *   (b) `audit-decisions/<slug>.md` — `peaks audit static --record` output.
 *   (c) `audit-prompts/<slug>.md` — methodology reference, written by the
 *       new `peaks audit artifact write --kind prompt` surface.
 *   (d) any other `<slug>.md` (at top level) with canonical YAML frontmatter
 *       declaring `metadata.type` ∈ the 8 `ProjectMemoryKind` values.
 *
 * On 2026-06-22 the Plan 4 audit archived 4 artifact types directly into
 * `.peaks/memory/` without going through the canonical CLI writer,
 * leaving 4 historical orphans (see migration in this slice).
 *
 * GUARD PHILOSOPHY (forward-looking, not historical purge):
 *
 *   - HARD checks fail CI. They cover the patterns the new writers prevent
 *     from recurring: top-level `.json` files other than `index.json`,
 *     forbidden top-level subdirectories, missing `metadata.type` on
 *     files written by the new writers (verified via writer round-trip
 *     tests in `tests/unit/services/audit/artifact-writer.test.ts`).
 *
 *   - SOFT checks (informational only, never fail CI) list legacy
 *     non-compliance as `softWarnings`. A separate cleanup slice would
 *     address them; this slice does not.
 *
 * The historical 4 orphans are migrated by this slice, so the HARD
 * checks pass after migration. Legacy non-canonical files (e.g. the
 * `<!-- peaks-memory:start -->` marker convention used by some skill
 * memories, or plain narratives without frontmatter, or kinds outside
 * the 8-kind union) are tolerated as soft warnings.
 *
 * Mirrors `top-level-change-id-guard.test.ts` style: hermetic fs scan,
 * no mocks, no fixtures, no git dependency.
 */

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import { VALID_PROJECT_MEMORY_KINDS } from '../../../src/services/memory/project-memory-service.js';

const REPO_ROOT = resolve(__dirname, '..', '..', '..');
const MEMORY_DIR = join(REPO_ROOT, '.peaks', 'memory');
const ALLOWED_TOP_LEVEL_SUBDIRS = new Set(['audit-decisions', 'audit-prompts', 'archived', 'promotions']);

interface ScanResult {
  /** HARD: top-level `.json` files other than `index.json`. */
  readonly forbiddenTopLevelJson: readonly string[];
  /** HARD: top-level subdirs other than `audit-decisions/`, `audit-prompts/`. */
  readonly forbiddenTopLevelSubdirs: readonly string[];
  /** SOFT: `.md` files with no YAML frontmatter at all. */
  readonly softMissingFrontmatter: readonly string[];
  /** SOFT: `.md` files whose frontmatter has no `metadata.type` field. */
  readonly softMissingMetadataType: readonly string[];
  /** SOFT: `.md` files whose `metadata.type` is not in the 8-kind union. */
  readonly softInvalidKind: readonly { file: string; kind: string }[];
}

function readFrontmatter(content: string): { frontmatter: string; body: string } | null {
  const normalized = content.replace(/\r\n/g, '\n');
  if (!normalized.startsWith('---\n')) return null;
  const endIndex = normalized.indexOf('\n---\n', 4);
  if (endIndex < 0) return null;
  return {
    frontmatter: normalized.slice(4, endIndex),
    body: normalized.slice(endIndex + '\n---\n'.length).trim(),
  };
}

/** Minimal YAML-ish frontmatter parser for the 3 fields we care about.
 *  Full recursive parser in `project-memory-service.ts` is too heavy for
 *  a guard. We accept: `name` / `description` at top level and
 *  `metadata.type` (nested two spaces under `metadata:`). */
function parseGuardFrontmatter(frontmatter: string): {
  name: string | null;
  description: string | null;
  metadataType: string | null;
} {
  const lines = frontmatter.split('\n');
  let name: string | null = null;
  let description: string | null = null;
  let metadataType: string | null = null;
  let inMetadata = false;
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '');
    if (line === 'metadata:' || line.startsWith('metadata:')) {
      inMetadata = true;
      continue;
    }
    // A non-indented top-level key exits metadata scope (best-effort;
    // this is a guard, not a YAML parser).
    if (inMetadata && line.length > 0 && !line.startsWith(' ') && !line.startsWith('\t')) {
      inMetadata = false;
    }
    if (inMetadata && line.trimStart().startsWith('type:')) {
      metadataType = line.trimStart().slice('type:'.length).trim();
    } else if (line.startsWith('name:')) {
      name = line.slice('name:'.length).trim();
    } else if (line.startsWith('description:')) {
      description = line.slice('description:'.length).trim();
    }
  }
  return { name, description, metadataType };
}

function scanShape(rootDir: string): ScanResult {
  const fs = require('node:fs') as typeof import('node:fs');
  const forbiddenTopLevelJson: string[] = [];
  const forbiddenTopLevelSubdirs: string[] = [];
  const softMissingFrontmatter: string[] = [];
  const softMissingMetadataType: string[] = [];
  const softInvalidKind: { file: string; kind: string }[] = [];

  const topEntries = fs.readdirSync(rootDir, { withFileTypes: true });
  for (const entry of topEntries) {
    if (entry.name.startsWith('.')) continue;
    if (entry.isFile() && entry.name.endsWith('.json')) {
      if (entry.name === 'index.json') continue;
      // `peaks memory extract --apply` writes a `.promotion.json` sidecar
      // per memory file as part of the promotion workflow (slice 2026-06-23
      // audit-artifact-writer-generalization). These sidecars are not part
      // of the memory contract — they are extracted-state metadata used by
      // the memory service. Tolerate them here; if `extract` ever changes
      // to write a different sidecar name, this allow-list will need an
      // update.
      if (entry.name.endsWith('.promotion.json')) continue;
      forbiddenTopLevelJson.push(entry.name);
      continue;
    }
    if (entry.isDirectory()) {
      if (!ALLOWED_TOP_LEVEL_SUBDIRS.has(entry.name)) {
        forbiddenTopLevelSubdirs.push(entry.name);
      }
      // Recurse into allowed subdirs to collect their soft warnings.
      const subdir = join(rootDir, entry.name);
      const subEntries = fs.readdirSync(subdir, { withFileTypes: true });
      for (const sub of subEntries) {
        if (sub.name.startsWith('.')) continue;
        if (sub.isFile() && sub.name.endsWith('.md')) {
          scanMarkdown(join(subdir, sub.name), {
            softMissingFrontmatter,
            softMissingMetadataType,
            softInvalidKind,
          });
        }
      }
      continue;
    }
    if (entry.isFile() && entry.name.endsWith('.md')) {
      scanMarkdown(join(rootDir, entry.name), {
        softMissingFrontmatter,
        softMissingMetadataType,
        softInvalidKind,
      });
    }
  }
  return {
    forbiddenTopLevelJson,
    forbiddenTopLevelSubdirs,
    softMissingFrontmatter,
    softMissingMetadataType,
    softInvalidKind,
  };
}

function scanMarkdown(
  filePath: string,
  out: {
    softMissingFrontmatter: string[];
    softMissingMetadataType: string[];
    softInvalidKind: { file: string; kind: string }[];
  },
): void {
  const fs = require('node:fs') as typeof import('node:fs');
  const content = fs.readFileSync(filePath, 'utf8');
  const parsed = readFrontmatter(content);
  if (parsed === null) {
    out.softMissingFrontmatter.push(filePath);
    return;
  }
  const { metadataType } = parseGuardFrontmatter(parsed.frontmatter);
  if (!metadataType) {
    out.softMissingMetadataType.push(filePath);
    return;
  }
  if (!(VALID_PROJECT_MEMORY_KINDS as readonly string[]).includes(metadataType)) {
    out.softInvalidKind.push({ file: filePath, kind: metadataType });
  }
}

// ---------------------------------------------------------------------------
// HARD checks (fail CI if violated)
// ---------------------------------------------------------------------------

describe('memory-shape guard — HARD checks (slice 2026-06-26-audit-artifact-writer-generalization)', () => {
  test('AC-1: no top-level .json files under .peaks/memory/ except index.json', () => {
    const result = scanShape(MEMORY_DIR);
    expect(result.forbiddenTopLevelJson).toEqual([]);
  });

  test('AC-5: top-level subdirs are limited to audit-decisions/, audit-prompts/, archived/, promotions/', () => {
    const result = scanShape(MEMORY_DIR);
    expect(result.forbiddenTopLevelSubdirs).toEqual([]);
  });

  test('AC-6: full scan completes in < 500ms (5 iterations, generous budget)', () => {
    const start = performance.now();
    for (let i = 0; i < 5; i += 1) scanShape(MEMORY_DIR);
    const elapsed = performance.now() - start;
    expect(elapsed).toBeLessThan(500);
  });
});

// ---------------------------------------------------------------------------
// SOFT checks (informational — list legacy non-compliance for follow-up)
// ---------------------------------------------------------------------------

describe('memory-shape guard — SOFT warnings (informational, never fail CI)', () => {
  test('reports legacy .md files missing frontmatter (informational only)', () => {
    const result = scanShape(MEMORY_DIR);
    // We don't assert zero — we assert the scanner can SEE them.
    // (Tests below prove the scanner works on synthetic inputs.)
    expect(Array.isArray(result.softMissingFrontmatter)).toBe(true);
  });

  test('reports legacy .md files missing metadata.type (informational only)', () => {
    const result = scanShape(MEMORY_DIR);
    expect(Array.isArray(result.softMissingMetadataType)).toBe(true);
  });

  test('reports legacy .md files with metadata.type outside the 8-kind union (informational)', () => {
    const result = scanShape(MEMORY_DIR);
    expect(Array.isArray(result.softInvalidKind)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Synthetic orphan detection (proves the scanner actually detects the
// historical failure modes — AC-7)
// ---------------------------------------------------------------------------

describe('memory-shape guard — synthetic orphan detection (proves scanner works)', () => {
  let tmpDir: string;

  beforeAll(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'memory-shape-guard-'));
  });

  afterAll(() => {
    if (tmpDir) rmSync(tmpDir, { recursive: true, force: true });
  });

  test('AC-7a: orphan raw .json (the round1/round2 historical case) is detected', () => {
    const orphanDir = join(tmpDir, 'case-a');
    mkdirSync(orphanDir, { recursive: true });
    writeFileSync(join(orphanDir, 'index.json'), '{}'); // pretend this is index.json
    writeFileSync(join(orphanDir, 'orphan-round1.json'), '{"p1_p2_p3_verification":{}}');
    const result = scanShape(orphanDir);
    expect(result.forbiddenTopLevelJson).toContain('orphan-round1.json');
  });

  test('AC-7b: orphan missing-frontmatter .md is detected as soft warning', () => {
    const orphanDir = join(tmpDir, 'case-b');
    mkdirSync(orphanDir, { recursive: true });
    writeFileSync(
      join(orphanDir, 'narrative.md'),
      '# narrative with no frontmatter\n\nThis file has no frontmatter.\n',
    );
    const result = scanShape(orphanDir);
    expect(result.softMissingFrontmatter.some((p) => p.endsWith(`${sep}narrative.md`))).toBe(true);
  });

  test('AC-7c: orphan invalid metadata.type is detected as soft warning', () => {
    const orphanDir = join(tmpDir, 'case-c');
    mkdirSync(orphanDir, { recursive: true });
    writeFileSync(
      join(orphanDir, 'bad-kind.md'),
      [
        '---',
        'name: bad-kind',
        'description: bad kind example',
        'metadata:',
        '  type: bogus-kind',
        '---',
        '',
        '# bad',
        '',
      ].join('\n'),
    );
    const result = scanShape(orphanDir);
    expect(result.softInvalidKind.some((k) => k.file.endsWith(`${sep}bad-kind.md`))).toBe(true);
  });

  test('AC-7d: forbidden top-level subdir is detected', () => {
    const orphanDir = join(tmpDir, 'case-d');
    mkdirSync(join(orphanDir, 'mystery-subdir'), { recursive: true });
    const result = scanShape(orphanDir);
    expect(result.forbiddenTopLevelSubdirs).toContain('mystery-subdir');
  });

  test('AC-7e: a fully compliant memory entry produces no violations', () => {
    const orphanDir = join(tmpDir, 'case-e');
    mkdirSync(orphanDir, { recursive: true });
    writeFileSync(
      join(orphanDir, 'good.md'),
      [
        '---',
        'name: good-entry',
        'description: fully compliant memory',
        'metadata:',
        '  type: project',
        '  artifactType: narrative',
        '  sourceArtifact: src/services/audit/artifact-writer.ts',
        '  createdAt: 2026-06-26',
        '---',
        '',
        '# Good entry',
        '',
        'Body text.',
        '',
      ].join('\n'),
    );
    const result = scanShape(orphanDir);
    expect(result.forbiddenTopLevelJson).toEqual([]);
    expect(result.forbiddenTopLevelSubdirs).toEqual([]);
    expect(result.softMissingFrontmatter).toEqual([]);
    expect(result.softMissingMetadataType).toEqual([]);
    expect(result.softInvalidKind).toEqual([]);
  });
});
