/**
 * `peaks context <sub>` — CLI surface for the ContextBuilder.
 * Per spec §4.1 — these commands are the only sanctioned entry point;
 * peaks-rd / peaks-qa / peaks-mut invoke them programmatically.
 */
import { Command } from 'commander';
import { readFile } from 'node:fs/promises';
import { buildContext } from '../../services/context/context-builder.js';
import { ContextJsonSchema } from '../../services/context/context-schema.js';
import type { DocFetcher } from '../../services/context/doc-retriever.js';

export interface ContextCommandsOptions {
  readonly fetcher: DocFetcher;
}

export function createContextCommands(options: ContextCommandsOptions): Command {
  const context = new Command('context').description(
    'peaks-context: build versioned, version-locked context.json (spec §4.1)'
  );

  context
    .command('build')
    .requiredOption('--goal <text>', 'user request goal')
    .requiredOption('--project <path>', 'project root')
    .option('--audience <role>', 'peaks-rd | peaks-qa | peaks-mut | all', 'all')
    .option('--deps-mode <mode>', 'locked | latest', 'locked')
    .option('--doc-budget-tokens <n>', 'token budget for renderer', '8000')
    .requiredOption('--out <path>', 'output path for context.json')
    .option('--json', 'machine-readable output', false)
    .action(async (opts: {
      goal: string;
      project: string;
      audience: string;
      depsMode: string;
      docBudgetTokens: string;
      out: string;
      json: boolean;
    }) => {
      const ctx = await buildContext({
        goal: opts.goal,
        project: opts.project,
        audience: opts.audience,
        depsMode: opts.depsMode,
        docBudgetTokens: Number(opts.docBudgetTokens),
        out: opts.out,
        fetcher: options.fetcher,
      });
      if (opts.json) {
        process.stdout.write(JSON.stringify({ ok: true, sha256: ctx.sha256 }) + '\n');
      } else {
        process.stdout.write(`context.json written: ${opts.out}\nsha256: ${ctx.sha256}\n`);
      }
    });

  context
    .command('validate <file>')
    .action(async (file: string) => {
      const raw = await readFile(file, 'utf8');
      const parsed = JSON.parse(raw);
      const result = ContextJsonSchema.safeParse(parsed);
      if (!result.success) {
        process.stderr.write(`INVALID: ${result.error.message}\n`);
        process.exit(2);
      }
      process.stdout.write(`OK: ${file}\n`);
    });

  context
    .command('inspect <file>')
    .action(async (file: string) => {
      const raw = await readFile(file, 'utf8');
      const ctx = JSON.parse(raw);
      process.stdout.write([
        `version: ${ctx.version}`,
        `goal: ${ctx.goal}`,
        `sha256: ${ctx.sha256}`,
        `deps: ${Object.keys(ctx.collector.deps).join(', ')}`,
        `fetchedDocs: ${ctx.docRetriever.fetchedDocs.length}`,
        `skipped: ${ctx.docRetriever.skipped.length}`,
        `truncated: ${ctx.renderer.truncated}`,
        `audience: ${ctx.renderer.audience}`,
      ].join('\n') + '\n');
    });

  context
    .command('schema')
    .action(async () => {
      // Pre-flight fix #3: read from the canonical schemas/context.schema.json
      // (generated by Task 12) instead of serializing Zod internals at runtime.
      // Both files must agree; if schema.json is missing, this command fails
      // with a clear message pointing at Task 12.
      const fs = await import('node:fs/promises');
      try {
        const content = await fs.readFile('schemas/context.schema.json', 'utf8');
        process.stdout.write(content + '\n');
      } catch {
        process.stderr.write(
          'BLOCKED: schemas/context.schema.json not found.\n' +
          'Run Task 12 of Plan 1 to generate it.\n'
        );
        process.exit(2);
      }
    });

  return context;
}